### PR TITLE
jackson 2.10.1

### PR DESCRIPTION
**Pull request by sullis**
release notes:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.1

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
@dependabot-bot Doesn't work for some reason. Should be done automatically.

**Comment by whiskeysierra** [comment]
@sullis Thanks for the contribution! :tada:

**Comment by whiskeysierra** [comment]
Officially we need signed commits. Would you be able to sign them and force-push?

**Comment by sullis** [comment]
ready for review

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
Github still complains about unsigned commits

**Comment by sullis** [comment]
Weird.  There is only 1 commit.  The commit includes "Signed-off-by"

**Comment by whiskeysierra** [comment]
> Weird. There is only 1 commit. The commit includes "Signed-off-by"

I believe that's something different. See https://help.github.com/articles/about-gpg/

**Pull request closed without merging**
