### PR TITLE
Add further nullability annotations to improve interop

### PR DESCRIPTION
**Pull request by orrc**
## Description
This PR marks more method parameters as explicitly nullable.
There are already lots of these annotations in place, but adding a few more makes interoperability with Kotlin a bit smoother, for example.

## Motivation and Context
Using this library with Kotlin is currently giving us some compiler errors when enabling [strict JSR-305 support](https://kotlinlang.org/docs/java-interop.html#jsr-305-support).

For example, even although the underlying `ProblemBuilder#withDetail` method explicitly allows a `null` string value, Kotlin somehow isn't able to infer that `detail` parameter in the `Problem#valueOf()` method is also nullable.

Hence we see compiler errors when trying to pass in a nullable string, e.g. the `message` field of a `kotlin.Throwable`:
image

Compiling against the changes in this PR resolved this class of errors throughout our project.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
None of the above?

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@orrc Can you cryptographically sign your commits? https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits

**Comment by orrc** [comment]
> Can you cryptographically sign your commits?

I have waved the theatrical wand of security and the commits are now signed… ✨ 😄

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
Thanks and your contribution is very much appreciated! 🎉

**Pull request merged**
