### PR TITLE
Remove JAX-RS dependency

### LINKED ISSUE #51: Remove JaxRS dependency
The dependency on JAX-RS 2 is hard because you can't use the lib with another one that depends on JAX-RS 1.
Especially you can't use it with spring-cloud-netflix as Ribbon and Eureka both use jersey1 (see https://github.com/spring-cloud/spring-cloud-netflix/issues/846)

It seems to me that only the Status/StatusType classes are used from JAX-RS. This doesn't represent a lot of code so it would be easy to duplicate. Also, it's always nice to remove a dependency and will make the lib smaller.

Of course I can PR if you want (and I would also do the PR for problem-spring-web).

Context : I want to bring Problem errors to [JHipster](http://www.jhipster.tech/) which uses Spring-Cloud/Netflix/Eureka/Ribbon

### PR DESCRIPTION
**Pull request by cbornet**
Replace JAX-RS Status class by internal one

Fix #51

### CODE REVIEW

**Comment by whiskeysierra** [comment]
fromStatusCode is only used in a test. I think we could omit it for now.

**Comment by cbornet** [comment]
fromStatusCode removed

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
@cbornet I released it as 0.20.0. Thanks for the contribution!

**Comment by cbornet** [comment]
Great ! I'll do the adaptation to the Spring lib now.

**Pull request merged**
